### ISSUE TITLE
Buggy examples

### ISSUE THREAD

**Issue by bloyl** [hnnsolver/hnn-core#85]
Hi all, 
I was just trying the examples in trunk on macos and was unable to get any of the 3 to run.

1) plot_simulate_somato fails looking for data (/Users/bloyl/mne_data/MNE-somato-data/MEG/somato/sef_raw_sss.fif) maybe the mne dataset has reorganized?

2) plot_simulate_alpha.py and plot_simulate_evoked both fail with a variant of
```
File "/Users/bloyl/Projects/hnn-core/hnn_core/basket.py", line 27, in _biophysics
    self.soma.insert('hh2')
ValueError: argument not a density mechanism name.

```

**Comment by jasmainak** [comment]
Try adding this line at the beginning of your script:

```py
from neuron import h

h.nrn_load_dll("../x86_64/.libs/libnrnmech.so")
```

**Comment by jasmainak** [comment]
ps: why are you coding on Saturday night? :)

**Comment by bloyl** [comment]
That solved it. at least for the 2...
 :) You mean not everyone spends there Saturdays this way?

**Comment by jasmainak** [comment]
If you figure out a more permanent solution, I'm happy to accept a PR :)

**Comment by jasmainak** [comment]
@bloyl this should be closed by https://github.com/hnnsolver/hnn-core/issues/85 -- a more permanent fix I hope.
